# Generated by Django 5.2 on 2026-03-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='출판사명')),
                ('supply_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='공급률(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '출판사',
                'verbose_name_plural': '출판사 목록',
                'db_table': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='시리즈')),
                ('name', models.CharField(max_length=255, verbose_name='교재명')),
                ('list_price', models.IntegerField(verbose_name='정가(원)')),
                ('is_returnable', models.BooleanField(default=True, verbose_name='반품 가능')),
                ('is_active', models.BooleanField(default=True, verbose_name='주문 가능')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.publisher', verbose_name='출판사')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재 목록',
                'db_table': 'books',
                'ordering': ['publisher', 'series', 'sort_order', 'name'],
            },
        ),
    ]
