# Generated by Django 5.2 on 2026-03-13 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_db_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['publisher', 'series', 'month', 'sort_order', 'name'], 'verbose_name': '교재', 'verbose_name_plural': '교재 목록'},
        ),
        migrations.AddField(
            model_name='book',
            name='agencies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'agency'}, related_name='available_books', to=settings.AUTH_USER_MODEL, verbose_name='취급 업체'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.CharField(blank=True, choices=[('', '통합'), ('1', '1학년'), ('2', '2학년')], default='', max_length=20, verbose_name='학년'),
        ),
        migrations.AddField(
            model_name='book',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], null=True, verbose_name='월'),
        ),
    ]
