# Generated by Django 5.2 on 2026-03-02 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(blank=True, max_length=100, verbose_name='대표자명')),
                ('biz_no', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='팩스')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
            ],
            options={
                'verbose_name': '업체 상세정보',
                'verbose_name_plural': '업체 상세정보',
                'db_table': 'agency_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login_id', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('role', models.CharField(choices=[('admin', '총판'), ('agency', '업체'), ('teacher', '선생님')], max_length=10, verbose_name='역할')),
                ('name', models.CharField(max_length=100, verbose_name='이름/업체명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True, verbose_name='비번 변경 필요')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, limit_choices_to={'role': 'agency'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='소속 업체')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
            },
        ),
    ]
