# Generated by Django 5.2 on 2026-03-08 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to=settings.AUTH_USER_MODEL, verbose_name='대상 사용자')),
            ],
            options={
                'verbose_name': '초대 토큰',
                'verbose_name_plural': '초대 토큰 목록',
                'db_table': 'invite_tokens',
            },
        ),
    ]
