# Generated by Django 5.2 on 2026-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_agency_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='간편주문 코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_slug',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='간편주문 링크(레거시)'),
        ),
    ]
