# Generated by Django 5.2 on 2026-03-09 08:17

import random
import string

from django.db import migrations


def populate_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    chars = string.ascii_lowercase + string.digits
    used = set()
    for user in User.objects.filter(role='agency', agency_code__isnull=True):
        while True:
            code = ''.join(random.choices(chars, k=6))
            if code not in used:
                used.add(code)
                break
        user.agency_code = code
        user.save(update_fields=['agency_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_agency_code'),
    ]

    operations = [
        migrations.RunPython(populate_codes, migrations.RunPython.noop),
    ]
