# Generated by Django 5.2 on 2026-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_is_individual_and_supply_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='비밀번호(평문)'),
        ),
    ]
