# Generated by Django 5.2 on 2026-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_category',
            field=models.CharField(blank=True, help_text='아이센, 미래정보, 참다손 등', max_length=30, verbose_name='업체 분류'),
        ),
    ]
