# Generated by Django 5.2 on 2026-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_fields_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ledger_format',
            field=models.CharField(blank=True, choices=[('full', '정석(정가/공급률)'), ('simple', '간소화(수량만)')], default='full', max_length=10, verbose_name='거래원장 형식'),
        ),
    ]
