# Generated by Django 5.2 on 2026-03-02 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학교명')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='휴대폰')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='팩스')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL, verbose_name='소속 업체')),
            ],
            options={
                'verbose_name': '배송지(학교)',
                'verbose_name_plural': '배송지 목록',
                'db_table': 'delivery_addresses',
                'ordering': ['agency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '접수'), ('shipping', '발송중'), ('delivered', '발송완료'), ('cancelled', '취소')], default='pending', max_length=10, verbose_name='상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='주문일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.PROTECT, related_name='agency_orders', to=settings.AUTH_USER_MODEL, verbose_name='업체')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.deliveryaddress', verbose_name='배송지')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_orders', to=settings.AUTH_USER_MODEL, verbose_name='선생님')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('list_price', models.IntegerField(verbose_name='정가(스냅샷)')),
                ('supply_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='공급률(스냅샷)')),
                ('unit_price', models.IntegerField(verbose_name='단가')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='books.book', verbose_name='교재')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상세',
                'verbose_name_plural': '주문 상세',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='입금액')),
                ('paid_at', models.DateField(verbose_name='입금일')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='업체')),
            ],
            options={
                'verbose_name': '입금 내역',
                'verbose_name_plural': '입금 내역',
                'db_table': 'payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=30, unique=True, verbose_name='반품번호')),
                ('status', models.CharField(choices=[('requested', '신청'), ('confirmed', '확정'), ('rejected', '거절')], default='requested', max_length=10, verbose_name='상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='신청일시')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확정일시')),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.PROTECT, related_name='agency_returns', to=settings.AUTH_USER_MODEL, verbose_name='업체')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.deliveryaddress', verbose_name='배송지')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_returns', to=settings.AUTH_USER_MODEL, verbose_name='선생님')),
            ],
            options={
                'verbose_name': '반품',
                'verbose_name_plural': '반품 목록',
                'db_table': 'returns',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.IntegerField(verbose_name='요청수량')),
                ('confirmed_qty', models.IntegerField(blank=True, null=True, verbose_name='확정수량')),
                ('list_price', models.IntegerField(verbose_name='정가(스냅샷)')),
                ('supply_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='공급률(스냅샷)')),
                ('unit_price', models.IntegerField(verbose_name='단가')),
                ('requested_amount', models.IntegerField(verbose_name='요청금액')),
                ('confirmed_amount', models.IntegerField(blank=True, null=True, verbose_name='확정금액')),
                ('adjusted_amount', models.IntegerField(default=0, verbose_name='조정금액')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='books.book', verbose_name='교재')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return', verbose_name='반품')),
            ],
            options={
                'verbose_name': '반품 상세',
                'verbose_name_plural': '반품 상세',
                'db_table': 'return_items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agency', 'ordered_at'], name='orders_agency__4e36e2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'ordered_at'], name='orders_status_d655ed_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['book'], name='order_items_book_id_81dc59_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['agency', 'paid_at'], name='payments_agency__4ca04d_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['agency', 'requested_at'], name='returns_agency__3e70ab_idx'),
        ),
    ]
