# Generated by Django 5.2 on 2026-03-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_tracking_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', '이메일'), ('sms', '문자')], max_length=10, verbose_name='수신 채널')),
                ('account_label', models.CharField(blank=True, max_length=20, verbose_name='계정')),
                ('sender', models.CharField(max_length=200, verbose_name='발신자')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('received_at', models.DateTimeField(verbose_name='수신 시각')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('imap_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IMAP 키')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='orders.order', verbose_name='연결 주문')),
            ],
            options={
                'verbose_name': '수신 메시지',
                'verbose_name_plural': '수신 메시지 목록',
                'db_table': 'inbox_messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
