# Generated by Django 5.2 on 2026-03-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_inbox_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inbox_attachments/%Y/%m/', verbose_name='파일')),
                ('filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 타입')),
                ('size', models.IntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.inboxmessage', verbose_name='수신 메시지')),
            ],
            options={
                'verbose_name': '수신 첨부파일',
                'verbose_name_plural': '수신 첨부파일',
                'db_table': 'inbox_attachments',
            },
        ),
    ]
