# Generated by Django 5.2 on 2026-03-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_inboxmessage_is_read_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('action', models.CharField(choices=[('visit', '링크 접속'), ('register', '신규 등록'), ('order', '주문 완료')], max_length=20, verbose_name='행동')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='접속 시각')),
                ('agency', models.ForeignKey(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='link_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='업체')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_accesses', to=settings.AUTH_USER_MODEL, verbose_name='선생님')),
            ],
            options={
                'verbose_name': '간편링크 접속 이력',
                'verbose_name_plural': '간편링크 접속 이력',
                'db_table': 'link_access_logs',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['agency', 'accessed_at'], name='link_access_agency__82ecd2_idx')],
            },
        ),
    ]
