# Generated by Django 5.2 on 2026-03-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('orders', '0006_add_link_access_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_book_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='커스텀 교재명'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='books.book', verbose_name='교재'),
        ),
    ]
