# Generated by Django 5.2 on 2026-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_custom_book_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('simple', '간편주문'), ('teacher', '선생님'), ('inbox', '수신함'), ('admin', '관리자')], default='admin', max_length=10, verbose_name='주문 경로'),
        ),
    ]
