# Generated by Django 5.2 on 2026-03-10 06:19

from django.db import migrations, models


def migrate_teacher_to_simple(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(source='teacher').update(source='simple')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_order_source'),
    ]

    operations = [
        migrations.RunPython(migrate_teacher_to_simple, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('simple', '간편주문'), ('inbox', '수신함'), ('admin', '관리자')], default='admin', max_length=10, verbose_name='주문 경로'),
        ),
    ]
