# Generated by Django 5.2 on 2026-03-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_teacher_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('hanjin', '한진택배'), ('cj', 'CJ대한통운'), ('lotte', '롯데택배'), ('logen', '로젠택배'), ('post', '우체국택배'), ('direct', '직접배송'), ('other', '기타')], default='hanjin', max_length=10, verbose_name='택배사')),
                ('tracking_no', models.CharField(blank=True, max_length=50, verbose_name='운송장번호')),
                ('memo', models.TextField(blank=True, verbose_name='배송메모')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '배송',
                'verbose_name_plural': '배송 목록',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='shipments_order_i_649a3c_idx'), models.Index(fields=['tracking_no'], name='shipments_trackin_0edf92_idx')],
            },
        ),
    ]
