# Generated by Django 5.2 on 2026-03-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_db_improvements'),
        ('orders', '0010_add_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='연결 주문'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='custom_book_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='커스텀 교재명'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='books.book', verbose_name='교재'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(choices=[('hanjin', '한진택배'), ('direct', '직접배송')], default='hanjin', max_length=10, verbose_name='택배사'),
        ),
    ]
