# Generated by Django 5.2 on 2026-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_db_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('hanjin', '한진택배'), ('direct', '직접배송')], default='', max_length=10, verbose_name='배송방법'),
        ),
    ]
