# Generated by Django 5.2 on 2026-03-11 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0012_add_order_carrier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_create', '주문 생성'), ('order_edit', '주문 수정'), ('order_delete', '주문 삭제'), ('order_cancel', '주문 취소'), ('order_ship', '발송 처리'), ('order_deliver', '배송완료'), ('order_restore', '주문 복구'), ('return_create', '반품 신청'), ('return_confirm', '반품 확정'), ('return_reject', '반품 거절'), ('password_reset', '비밀번호 초기화'), ('user_toggle', '계정 활성/비활성')], max_length=20, verbose_name='액션')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='대상 ID')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=10, verbose_name='이전 상태')),
                ('new_status', models.CharField(choices=[('pending', '접수'), ('shipping', '발송중'), ('delivered', '발송완료'), ('cancelled', '취소')], max_length=10, verbose_name='변경 상태')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '주문 상태 이력',
                'verbose_name_plural': '주문 상태 이력',
                'db_table': 'order_status_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='orders.order', verbose_name='원주문'),
        ),
        migrations.AddField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('over_order', '과주문'), ('damaged', '파손'), ('wrong_item', '오배송'), ('exchange', '교체'), ('etc', '기타')], default='etc', max_length=15, verbose_name='반품 사유'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_no'], name='orders_trackin_e5b19b_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='대상 타입'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='수행자'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='주문'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
    ]
