# Generated by Django 5.2 on 2026-03-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auditlog_orderstatuslog_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('simple', '간편주문'), ('inbox', '수신함'), ('admin', '관리자'), ('call', '통화주문')], default='admin', max_length=10, verbose_name='주문 경로'),
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='call_recordings/%Y%m/', verbose_name='녹음파일')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='원본파일명')),
                ('caller_phone', models.CharField(blank=True, max_length=20, verbose_name='발신번호')),
                ('duration_sec', models.IntegerField(blank=True, null=True, verbose_name='통화시간(초)')),
                ('recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='녹음일시')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('parsed', '파싱완료'), ('ordered', '주문생성'), ('skipped', '건너뜀'), ('failed', '실패')], default='pending', max_length=12, verbose_name='처리상태')),
                ('transcript', models.TextField(blank=True, verbose_name='변환 텍스트')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='파싱 결과')),
                ('error_msg', models.CharField(blank=True, max_length=300, verbose_name='오류메시지')),
                ('source', models.CharField(blank=True, help_text='gdrive, webhook, browser 등', max_length=30, verbose_name='수신경로')),
                ('gdrive_file_id', models.CharField(blank=True, max_length=100, verbose_name='Google Drive 파일ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to='orders.order', verbose_name='생성된 주문')),
            ],
            options={
                'verbose_name': '통화 녹음',
                'verbose_name_plural': '통화 녹음 목록',
                'db_table': 'call_recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
