# Generated by Django 5.2 on 2026-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_call_recording_and_source_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_city', models.TimeField(default='11:20', verbose_name='시내 마감시간')),
                ('deadline_region', models.TimeField(default='13:50', verbose_name='지방 마감시간')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사이트 설정',
                'db_table': 'site_config',
            },
        ),
    ]
