# Generated by Django 5.2 on 2026-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='is_order',
            field=models.BooleanField(blank=True, null=True, verbose_name='주문 통화 여부'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='통화 요약'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('simple', '간편주문'), ('inbox', '수신함'), ('admin', '관리자'), ('call', '통화주문'), ('import', '극동임포트')], default='admin', max_length=10, verbose_name='주문 경로'),
        ),
    ]
