# Generated by Django 5.2 on 2026-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_call_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='전화번호'),
        ),
    ]
