# Generated by Django 5.2 on 2026-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_add_phone_to_inboxmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='서류명')),
                ('file', models.FileField(upload_to='business_docs/', verbose_name='파일')),
                ('auto_attach', models.BooleanField(default=True, verbose_name='자동 첨부')),
                ('order_no', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사업자 서류',
                'verbose_name_plural': '사업자 서류 목록',
                'db_table': 'business_documents',
                'ordering': ['order_no', 'name'],
            },
        ),
    ]
