# Generated by Django 5.2 on 2026-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_add_business_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='location_detail',
            field=models.CharField(blank=True, help_text='예: 4층 컴퓨터실, 관리실 경유', max_length=100, verbose_name='배송 위치 상세'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='region',
            field=models.CharField(blank=True, choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('regional', '지방')], max_length=10, verbose_name='지역 분류'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='요청 배송일'),
        ),
    ]
