# Generated by Django 5.2 on 2026-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_backfill_sms_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_teacher_copy',
            field=models.BooleanField(default=False, verbose_name='교사용'),
        ),
    ]
