# Generated by Django 5.2 on 2026-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_add_teacher_copy_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='수정됨'),
        ),
    ]
